[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
blake3 = "1.5.0"
digest = "0.10.7"
nanoserde = "0.1.35"
pico-args = "0.5.0"
ron = "0.8.1"
serde = { version = "1", features = ["derive"] }
